using System.Collections.Generic;
using Gyldendal.Api.CoreData.Contracts.Models;
// ReSharper disable UnusedAutoPropertyAccessor.Global

namespace Gyldendal.Api.CoreData.DataAccess.StaticLookups
{
	public static class Countries
	{
		public static List<Country> List = new List<Country>
		{
			new Country { Name = "Afghanistan ", Alpha2Code = "AF", Alpha3Code = "AFG" },
			new Country { Name = "Åland", Alpha2Code = "AX", Alpha3Code = "ALA" },
			new Country { Name = "Albanien ", Alpha2Code = "AL", Alpha3Code = "ALB" },
			new Country { Name = "Algeriet ", Alpha2Code = "DZ", Alpha3Code = "DZA" },
			new Country { Name = "Amerikansk Samoa", Alpha2Code = "AS", Alpha3Code = "ASM" },
			new Country { Name = "Andorra ", Alpha2Code = "AD", Alpha3Code = "AND" },
			new Country { Name = "Angola ", Alpha2Code = "AO", Alpha3Code = "AGO" },
			new Country { Name = "Anguilla", Alpha2Code = "AI", Alpha3Code = "AIA" },
			new Country { Name = "Antarktis", Alpha2Code = "AQ", Alpha3Code = "ATA" },
			new Country { Name = "Antigua &Barbuda ", Alpha2Code = "AG", Alpha3Code = "ATG" },
			new Country { Name = "Argentina ", Alpha2Code = "AR", Alpha3Code = "ARG" },
			new Country { Name = "Armenien ", Alpha2Code = "AM", Alpha3Code = "ARM" },
			new Country { Name = "Aruba", Alpha2Code = "AW", Alpha3Code = "ABW" },
			new Country { Name = "Australien ", Alpha2Code = "AU", Alpha3Code = "AUS" },
			new Country { Name = "Østrig ", Alpha2Code = "AT", Alpha3Code = "AUT" },
			new Country { Name = "Aserbajdsjan ", Alpha2Code = "AZ", Alpha3Code = "AZE" },
			new Country { Name = "Bahamas ", Alpha2Code = "BS", Alpha3Code = "BHS" },
			new Country { Name = "Bahrain ", Alpha2Code = "BH", Alpha3Code = "BHR" },
			new Country { Name = "Bangladesh ", Alpha2Code = "BD", Alpha3Code = "BGD" },
			new Country { Name = "Barbados ", Alpha2Code = "BB", Alpha3Code = "BRB" },
			new Country { Name = "Hviderusland", Alpha2Code = "BY", Alpha3Code = "BLR" },
			new Country { Name = "Belgien ", Alpha2Code = "BE", Alpha3Code = "BEL" },
			new Country { Name = "Belize ", Alpha2Code = "BZ", Alpha3Code = "BLZ" },
			new Country { Name = "Benin ", Alpha2Code = "BJ", Alpha3Code = "BEN" },
			new Country { Name = "Bermuda", Alpha2Code = "BM", Alpha3Code = "BMU" },
			new Country { Name = "Bhutan ", Alpha2Code = "BT", Alpha3Code = "BTN" },
			new Country { Name = "Bolivia ", Alpha2Code = "BO", Alpha3Code = "BOL" },
			new Country { Name = "Bosnien-Herzegovina ", Alpha2Code = "BA", Alpha3Code = "BIH" },
			new Country { Name = "Botswana ", Alpha2Code = "BW", Alpha3Code = "BWA" },
			new Country { Name = "Bouvetøen", Alpha2Code = "BV", Alpha3Code = "BVT" },
			new Country { Name = "Brasilien ", Alpha2Code = "BR", Alpha3Code = "BRA" },
			new Country { Name = "Det britiske territorium i Det Indiske Ocean", Alpha2Code = "IO", Alpha3Code = "IOT" },
			new Country { Name = "De britiske jomfruøerne", Alpha2Code = "VG", Alpha3Code = "VGB" },
			new Country { Name = "Brunei ", Alpha2Code = "BN", Alpha3Code = "BRN" },
			new Country { Name = "Bulgarien ", Alpha2Code = "BG", Alpha3Code = "BGR" },
			new Country { Name = "Burkina Faso ", Alpha2Code = "BF", Alpha3Code = "BFA" },
			new Country { Name = "Burundi ", Alpha2Code = "BI", Alpha3Code = "BDI" },
			new Country { Name = "Elfenbenskysten ", Alpha2Code = "CI", Alpha3Code = "CIV" },
			new Country { Name = "Cambodja ", Alpha2Code = "KH", Alpha3Code = "KHM" },
			new Country { Name = "Cameroun ", Alpha2Code = "CM", Alpha3Code = "CMR" },
			new Country { Name = "Canada ", Alpha2Code = "CA", Alpha3Code = "CAN" },
			new Country { Name = "Kapverdiske Øer ", Alpha2Code = "CV", Alpha3Code = "CPV" },
			new Country { Name = "Caymanøerne", Alpha2Code = "KY", Alpha3Code = "CYM" },
			new Country { Name = "Centralafrika ", Alpha2Code = "CF", Alpha3Code = "CAF" },
			new Country { Name = "Chad ", Alpha2Code = "TD", Alpha3Code = "TCD" },
			new Country { Name = "Chile ", Alpha2Code = "CL", Alpha3Code = "CHL" },
			new Country { Name = "Kina ", Alpha2Code = "CN", Alpha3Code = "CHN" },
			new Country { Name = "Juleøen", Alpha2Code = "CX", Alpha3Code = "CXR" },
			new Country { Name = "Cocosøerne", Alpha2Code = "CC", Alpha3Code = "CCK" },
			new Country { Name = "Colombia ", Alpha2Code = "CO", Alpha3Code = "COL" },
			new Country { Name = "Comorerne ", Alpha2Code = "KM", Alpha3Code = "COM" },
			new Country { Name = "Congo ", Alpha2Code = "CG", Alpha3Code = "COG" },
			new Country { Name = "Demokratiske republik Congo ", Alpha2Code = "CD", Alpha3Code = "COD" },
			new Country { Name = "Cookøerne", Alpha2Code = "CK", Alpha3Code = "COK" },
			new Country { Name = "Costa Rica ", Alpha2Code = "CR", Alpha3Code = "CRI" },
			new Country { Name = "Kroatien ", Alpha2Code = "HR", Alpha3Code = "HRV" },
			new Country { Name = "Cuba ", Alpha2Code = "CU", Alpha3Code = "CUB" },
			new Country { Name = "Cypern ", Alpha2Code = "CY", Alpha3Code = "CYP" },
			new Country { Name = "Tjekkiet ", Alpha2Code = "CZ", Alpha3Code = "CZE" },
			new Country { Name = "Danmark", Alpha2Code = "DK", Alpha3Code = "DNK" },
			new Country { Name = "Djibouti ", Alpha2Code = "DJ", Alpha3Code = "DJI" },
			new Country { Name = "Dominica ", Alpha2Code = "DM", Alpha3Code = "DMA" },
			new Country { Name = "Dominikanske Republik ", Alpha2Code = "DO", Alpha3Code = "DOM" },
			new Country { Name = "Ecuador ", Alpha2Code = "EC", Alpha3Code = "ECU" },
			new Country { Name = "Egypten ", Alpha2Code = "EG", Alpha3Code = "EGY" },
			new Country { Name = "El Salvador ", Alpha2Code = "SV", Alpha3Code = "SLV" },
			new Country { Name = "Ækvatorial Guinea ", Alpha2Code = "GQ", Alpha3Code = "GNQ" },
			new Country { Name = "Eritrea ", Alpha2Code = "ER", Alpha3Code = "ERI" },
			new Country { Name = "Estland ", Alpha2Code = "EE", Alpha3Code = "EST" },
			new Country { Name = "Etiopien ", Alpha2Code = "ET", Alpha3Code = "ETH" },
			new Country { Name = "Fiji ", Alpha2Code = "FK", Alpha3Code = "FLK" },
			new Country { Name = "Færøerne", Alpha2Code = "FO", Alpha3Code = "FRO" },
			new Country { Name = "Fijiøerne", Alpha2Code = "FJ", Alpha3Code = "FJI" },
			new Country { Name = "Finland ", Alpha2Code = "FI", Alpha3Code = "FIN" },
			new Country { Name = "Frankrig ", Alpha2Code = "FR", Alpha3Code = "FRA" },
			new Country { Name = "Fransk Guinea", Alpha2Code = "GF", Alpha3Code = "GUF" },
			new Country { Name = "Fransk Polynesien", Alpha2Code = "PF", Alpha3Code = "PYF" },
			new Country { Name = "Franske Sydlige og Antarktiske Territorier", Alpha2Code = "TF", Alpha3Code = "ATF" },
			new Country { Name = "Gabon ", Alpha2Code = "GA", Alpha3Code = "GAB" },
			new Country { Name = "Gambia ", Alpha2Code = "GM", Alpha3Code = "GMB" },
			new Country { Name = "Georgien ", Alpha2Code = "GE", Alpha3Code = "GEO" },
			new Country { Name = "Tyskland", Alpha2Code = "DE", Alpha3Code = "DEU" },
			new Country { Name = "Ghana ", Alpha2Code = "GH", Alpha3Code = "GHA" },
			new Country { Name = "Gibraltar", Alpha2Code = "GI", Alpha3Code = "GIB" },
			new Country { Name = "Grækenland ", Alpha2Code = "GR", Alpha3Code = "GRC" },
			new Country { Name = "Grønland", Alpha2Code = "GL", Alpha3Code = "GRL" },
			new Country { Name = "Grenada ", Alpha2Code = "GD", Alpha3Code = "GRD" },
			new Country { Name = "Grenadinerne ", Alpha2Code = "GP", Alpha3Code = "GLP" },
			new Country { Name = "Guam", Alpha2Code = "GU", Alpha3Code = "GUM" },
			new Country { Name = "Guatemala ", Alpha2Code = "GT", Alpha3Code = "GTM" },
			new Country { Name = "Guernsey", Alpha2Code = "GG", Alpha3Code = "GGY" },
			new Country { Name = "Guinea ", Alpha2Code = "GN", Alpha3Code = "GIN" },
			new Country { Name = "Guinea-Bissau ", Alpha2Code = "GW", Alpha3Code = "GNB" },
			new Country { Name = "Guyana ", Alpha2Code = "GY", Alpha3Code = "GUY" },
			new Country { Name = "Haiti ", Alpha2Code = "HT", Alpha3Code = "HTI" },
			new Country { Name = "Heard- og Mcdonaldøerne", Alpha2Code = "HM", Alpha3Code = "HMD" },
			new Country { Name = "Vatikanet", Alpha2Code = "VA", Alpha3Code = "VAT" },
			new Country { Name = "Honduras ", Alpha2Code = "HN", Alpha3Code = "HND" },
			new Country { Name = "Hong Kong", Alpha2Code = "HK", Alpha3Code = "HKG" },
			new Country { Name = "Ungarn", Alpha2Code = "HU", Alpha3Code = "HUN" },
			new Country { Name = "Island ", Alpha2Code = "IS", Alpha3Code = "ISL" },
			new Country { Name = "Indien ", Alpha2Code = "IN", Alpha3Code = "IND" },
			new Country { Name = "Indonesien ", Alpha2Code = "ID", Alpha3Code = "IDN" },
			new Country { Name = "Iran", Alpha2Code = "IR", Alpha3Code = "IRN" },
			new Country { Name = "Irak ", Alpha2Code = "IQ", Alpha3Code = "IRQ" },
			new Country { Name = "Irland ", Alpha2Code = "IE", Alpha3Code = "IRL" },
			new Country { Name = "Isle of Man", Alpha2Code = "IM", Alpha3Code = "IMN" },
			new Country { Name = "Israel ", Alpha2Code = "IL", Alpha3Code = "ISR" },
			new Country { Name = "Italien ", Alpha2Code = "IT", Alpha3Code = "ITA" },
			new Country { Name = "Jamaica ", Alpha2Code = "JM", Alpha3Code = "JAM" },
			new Country { Name = "Japan ", Alpha2Code = "JP", Alpha3Code = "JPN" },
			new Country { Name = "Jersey", Alpha2Code = "JE", Alpha3Code = "JEY" },
			new Country { Name = "Jordan ", Alpha2Code = "JO", Alpha3Code = "JOR" },
			new Country { Name = "Kasakhstan ", Alpha2Code = "KZ", Alpha3Code = "KAZ" },
			new Country { Name = "Kenya ", Alpha2Code = "KE", Alpha3Code = "KEN" },
			new Country { Name = "Kiribati ", Alpha2Code = "KI", Alpha3Code = "KIR" },
			new Country { Name = "Nordkorea", Alpha2Code = "KP", Alpha3Code = "PRK" },
			new Country { Name = "Sydkorea", Alpha2Code = "KR", Alpha3Code = "KOR" },
			new Country { Name = "Kuwait ", Alpha2Code = "KW", Alpha3Code = "KWT" },
			new Country { Name = "Kirgisistan ", Alpha2Code = "KG", Alpha3Code = "KGZ" },
			new Country { Name = "Laos ", Alpha2Code = "LA", Alpha3Code = "LAO" },
			new Country { Name = "Letland ", Alpha2Code = "LV", Alpha3Code = "LVA" },
			new Country { Name = "Libanon ", Alpha2Code = "LB", Alpha3Code = "LBN" },
			new Country { Name = "Lesotho ", Alpha2Code = "LS", Alpha3Code = "LSO" },
			new Country { Name = "Liberia ", Alpha2Code = "LR", Alpha3Code = "LBR" },
			new Country { Name = "Libyen ", Alpha2Code = "LY", Alpha3Code = "LBY" },
			new Country { Name = "Liechtenstein ", Alpha2Code = "LI", Alpha3Code = "LIE" },
			new Country { Name = "Litauen ", Alpha2Code = "LT", Alpha3Code = "LTU" },
			new Country { Name = "Luxembourg ", Alpha2Code = "LU", Alpha3Code = "LUX" },
			new Country { Name = "Macau", Alpha2Code = "MO", Alpha3Code = "MAC" },
			new Country { Name = "Makedonien (FYROM) ", Alpha2Code = "MK", Alpha3Code = "MKD" },
			new Country { Name = "Madagaskar ", Alpha2Code = "MG", Alpha3Code = "MDG" },
			new Country { Name = "Malawi ", Alpha2Code = "MW", Alpha3Code = "MWI" },
			new Country { Name = "Malaysia ", Alpha2Code = "MY", Alpha3Code = "MYS" },
			new Country { Name = "Maldiverne ", Alpha2Code = "MV", Alpha3Code = "MDV" },
			new Country { Name = "Mali ", Alpha2Code = "ML", Alpha3Code = "MLI" },
			new Country { Name = "Malta ", Alpha2Code = "MT", Alpha3Code = "MLT" },
			new Country { Name = "Marshall-øerne ", Alpha2Code = "MH", Alpha3Code = "MHL" },
			new Country { Name = "Martinique", Alpha2Code = "MQ", Alpha3Code = "MTQ" },
			new Country { Name = "Mauretanien ", Alpha2Code = "MR", Alpha3Code = "MRT" },
			new Country { Name = "Mauritius ", Alpha2Code = "MU", Alpha3Code = "MUS" },
			new Country { Name = "Mayotte", Alpha2Code = "YT", Alpha3Code = "MYT" },
			new Country { Name = "Mexico ", Alpha2Code = "MX", Alpha3Code = "MEX" },
			new Country { Name = "Mikronesien ", Alpha2Code = "FM", Alpha3Code = "FSM" },
			new Country { Name = "Moldova ", Alpha2Code = "MD", Alpha3Code = "MDA" },
			new Country { Name = "Monaco ", Alpha2Code = "MC", Alpha3Code = "MCO" },
			new Country { Name = "Mongoliet ", Alpha2Code = "MN", Alpha3Code = "MNG" },
			new Country { Name = "Montenegro", Alpha2Code = "ME", Alpha3Code = "MNE" },
			new Country { Name = "Montserrat", Alpha2Code = "MS", Alpha3Code = "MSR" },
			new Country { Name = "Marokko ", Alpha2Code = "MA", Alpha3Code = "MAR" },
			new Country { Name = "Mozambique ", Alpha2Code = "MZ", Alpha3Code = "MOZ" },
			new Country { Name = "Myanmar ", Alpha2Code = "MM", Alpha3Code = "MMR" },
			new Country { Name = "Namibia ", Alpha2Code = "NA", Alpha3Code = "NAM" },
			new Country { Name = "Nauru ", Alpha2Code = "NR", Alpha3Code = "NRU" },
			new Country { Name = "Nepal ", Alpha2Code = "NP", Alpha3Code = "NPL" },
			new Country { Name = "Nederlandene ", Alpha2Code = "NL", Alpha3Code = "NLD" },
			new Country { Name = "Antillerne", Alpha2Code = "AN", Alpha3Code = "ANT" },
			new Country { Name = "Ny Kaledonien", Alpha2Code = "NC", Alpha3Code = "NCL" },
			new Country { Name = "New Zealand ", Alpha2Code = "NZ", Alpha3Code = "NZL" },
			new Country { Name = "Nicaragua ", Alpha2Code = "NI", Alpha3Code = "NIC" },
			new Country { Name = "Niger ", Alpha2Code = "NE", Alpha3Code = "NER" },
			new Country { Name = "Nigeria ", Alpha2Code = "NG", Alpha3Code = "NGA" },
			new Country { Name = "Niue", Alpha2Code = "NU", Alpha3Code = "NIU" },
			new Country { Name = "Norfolk-øen", Alpha2Code = "NF", Alpha3Code = "NFK" },
			new Country { Name = "Nordmarianerne", Alpha2Code = "MP", Alpha3Code = "MNP" },
			new Country { Name = "Norge ", Alpha2Code = "NO", Alpha3Code = "NOR" },
			new Country { Name = "Oman ", Alpha2Code = "OM", Alpha3Code = "OMN" },
			new Country { Name = "Pakistan ", Alpha2Code = "PK", Alpha3Code = "PAK" },
			new Country { Name = "Palau ", Alpha2Code = "PW", Alpha3Code = "PLW" },
			new Country { Name = "Palestina ", Alpha2Code = "PS", Alpha3Code = "PSE" },
			new Country { Name = "Panama ", Alpha2Code = "PA", Alpha3Code = "PAN" },
			new Country { Name = "Papua New Guinea ", Alpha2Code = "PG", Alpha3Code = "PNG" },
			new Country { Name = "Paraguay ", Alpha2Code = "PY", Alpha3Code = "PRY" },
			new Country { Name = "Peru ", Alpha2Code = "PE", Alpha3Code = "PER" },
			new Country { Name = "Filippinerne ", Alpha2Code = "PH", Alpha3Code = "PHL" },
			new Country { Name = "Pitcairn", Alpha2Code = "PN", Alpha3Code = "PCN" },
			new Country { Name = "Polen ", Alpha2Code = "PL", Alpha3Code = "POL" },
			new Country { Name = "Portugal ", Alpha2Code = "PT", Alpha3Code = "PRT" },
			new Country { Name = "Puerto Rico", Alpha2Code = "PR", Alpha3Code = "PRI" },
			new Country { Name = "Qatar ", Alpha2Code = "QA", Alpha3Code = "QAT" },
			new Country { Name = "Réunion", Alpha2Code = "RE", Alpha3Code = "REU" },
			new Country { Name = "Rumænien ", Alpha2Code = "RO", Alpha3Code = "ROU" },
			new Country { Name = "Rusland ", Alpha2Code = "RU", Alpha3Code = "RUS" },
			new Country { Name = "Rwanda ", Alpha2Code = "RW", Alpha3Code = "RWA" },
			new Country { Name = "Sankt Helena", Alpha2Code = "SH", Alpha3Code = "SHN" },
			new Country { Name = "Sankt Kitts-Nevis ", Alpha2Code = "KN", Alpha3Code = "KNA" },
			new Country { Name = "Sankt Lucia", Alpha2Code = "LC", Alpha3Code = "LCA" },
			new Country { Name = "Sankt Pierre og Miquelon", Alpha2Code = "PM", Alpha3Code = "SPM" },
			new Country { Name = "Sankt Vincent & Grenadinerne", Alpha2Code = "VC", Alpha3Code = "VCT" },
			new Country { Name = "Sankt Barthélemy", Alpha2Code = "BL", Alpha3Code = "BLM" },
			new Country { Name = "Sankt Martin", Alpha2Code = "MF", Alpha3Code = "MAF" },
			new Country { Name = "Samoa ", Alpha2Code = "WS", Alpha3Code = "WSM" },
			new Country { Name = "San Marino ", Alpha2Code = "SM", Alpha3Code = "SMR" },
			new Country { Name = "Sao Tomé & Principe ", Alpha2Code = "ST", Alpha3Code = "STP" },
			new Country { Name = "Saudi Arabien ", Alpha2Code = "SA", Alpha3Code = "SAU" },
			new Country { Name = "Senegal ", Alpha2Code = "SN", Alpha3Code = "SEN" },
			new Country { Name = "Serbien", Alpha2Code = "RS", Alpha3Code = "SRB" },
			new Country { Name = "Seychellerne ", Alpha2Code = "SC", Alpha3Code = "SYC" },
			new Country { Name = "Sierra Leone ", Alpha2Code = "SL", Alpha3Code = "SLE" },
			new Country { Name = "Singapore ", Alpha2Code = "SG", Alpha3Code = "SGP" },
			new Country { Name = "Slovakiet ", Alpha2Code = "SK", Alpha3Code = "SVK" },
			new Country { Name = "Slovenien ", Alpha2Code = "SI", Alpha3Code = "SVN" },
			new Country { Name = "Salomonøerne ", Alpha2Code = "SB", Alpha3Code = "SLB" },
			new Country { Name = "Somalia", Alpha2Code = "SO", Alpha3Code = "SOM" },
			new Country { Name = "Sydafrika ", Alpha2Code = "ZA", Alpha3Code = "ZAF" },
			new Country { Name = "Falklandsøerne", Alpha2Code = "GS", Alpha3Code = "SGS" },
			new Country { Name = "Sydsudan", Alpha2Code = "SS", Alpha3Code = "SSD" },
			new Country { Name = "Spanien ", Alpha2Code = "ES", Alpha3Code = "ESP" },
			new Country { Name = "Sri Lanka ", Alpha2Code = "LK", Alpha3Code = "LKA" },
			new Country { Name = "Sudan ", Alpha2Code = "SD", Alpha3Code = "SDN" },
			new Country { Name = "Surinam ", Alpha2Code = "SR", Alpha3Code = "SUR" },
			new Country { Name = "Svalbard", Alpha2Code = "SJ", Alpha3Code = "SJM" },
			new Country { Name = "Swaziland ", Alpha2Code = "SZ", Alpha3Code = "SWZ" },
			new Country { Name = "Sverige ", Alpha2Code = "SE", Alpha3Code = "SWE" },
			new Country { Name = "Schweiz ", Alpha2Code = "CH", Alpha3Code = "CHE" },
			new Country { Name = "Syrien ", Alpha2Code = "SY", Alpha3Code = "SYR" },
			new Country { Name = "Taiwan ", Alpha2Code = "TW", Alpha3Code = "TWN" },
			new Country { Name = "Tadjikistan ", Alpha2Code = "TJ", Alpha3Code = "TJK" },
			new Country { Name = "Tanzania ", Alpha2Code = "TZ", Alpha3Code = "TZA" },
			new Country { Name = "Thailand ", Alpha2Code = "TH", Alpha3Code = "THA" },
			new Country { Name = "Østtimor ", Alpha2Code = "TL", Alpha3Code = "TLS" },
			new Country { Name = "Togo ", Alpha2Code = "TG", Alpha3Code = "TGO" },
			new Country { Name = "Tokelau", Alpha2Code = "TK", Alpha3Code = "TKL" },
			new Country { Name = "Tonga ", Alpha2Code = "TO", Alpha3Code = "TON" },
			new Country { Name = "Trinidad & Tobago ", Alpha2Code = "TT", Alpha3Code = "TTO" },
			new Country { Name = "Tunesien ", Alpha2Code = "TN", Alpha3Code = "TUN" },
			new Country { Name = "Tyrkiet ", Alpha2Code = "TR", Alpha3Code = "TUR" },
			new Country { Name = "Turkmenistan ", Alpha2Code = "TM", Alpha3Code = "TKM" },
			new Country { Name = "Turks- og Caicosøerne", Alpha2Code = "TC", Alpha3Code = "TCA" },
			new Country { Name = "Tuvalu ", Alpha2Code = "TV", Alpha3Code = "TUV" },
			new Country { Name = "Uganda ", Alpha2Code = "UG", Alpha3Code = "UGA" },
			new Country { Name = "Ukraine ", Alpha2Code = "UA", Alpha3Code = "UKR" },
			new Country { Name = "Forenede Arab. Emirater ", Alpha2Code = "AE", Alpha3Code = "ARE" },
			new Country { Name = "Storbritannien ", Alpha2Code = "GB", Alpha3Code = "GBR" },
			new Country { Name = "USA", Alpha2Code = "US", Alpha3Code = "USA" },
			new Country { Name = "Uruguay ", Alpha2Code = "UY", Alpha3Code = "URY" },
			new Country { Name = "USA's ydre småøer", Alpha2Code = "UM", Alpha3Code = "UMI" },
			new Country { Name = "Usbekistan ", Alpha2Code = "UZ", Alpha3Code = "UZB" },
			new Country { Name = "Vanuatu ", Alpha2Code = "VU", Alpha3Code = "VUT" },
			new Country { Name = "Venezuela ", Alpha2Code = "VE", Alpha3Code = "VEN" },
			new Country { Name = "Vietnam ", Alpha2Code = "VN", Alpha3Code = "VNM" },
			new Country { Name = "Jomfruøerne", Alpha2Code = "VI", Alpha3Code = "VIR" },
			new Country { Name = "Wallis og Futuna", Alpha2Code = "WF", Alpha3Code = "WLF" },
			new Country { Name = "Vest-Sahara", Alpha2Code = "EH", Alpha3Code = "ESH" },
			new Country { Name = "Yemen ", Alpha2Code = "YE", Alpha3Code = "YEM" },
			new Country { Name = "Zambia ", Alpha2Code = "ZM", Alpha3Code = "ZMB" },
			new Country { Name = "Zimbabwe ", Alpha2Code = "ZW", Alpha3Code = "ZWE" },
					
		};		
		
	}
}
