//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsolidatedContributorView
    {
        public string contributor_id { get; set; }
        public string contributor_navn { get; set; }
        public string contributor_langbeskrivelse { get; set; }
        public string contributor_foto { get; set; }
        public string contributor_langBeskrivelse_tekst { get; set; }
        public string contributor_fornavn { get; set; }
        public string contributor_efternavn { get; set; }
        public string contributor_profileLink { get; set; }
        public string Forfatternr { get; set; }
        public string contributor_information { get; set; }
    }
}
