//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsolidatedWorkReviewView
    {
        public int ReviewAttributeId { get; set; }
        public int WorkReviewId { get; set; }
        public int WorkId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string omForfatteren { get; set; }
        public string teksttype { get; set; }
        public string anmeldelse { get; set; }
        public string kortOmBogen { get; set; }
        public Nullable<bool> kladde { get; set; }
        public Nullable<System.DateTime> Lastupdated { get; set; }
        public int Website_Enum_Id { get; set; }
    }
}
