//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GGA_Forfatter
    {
        public string forfatter_id { get; set; }
        public string forfatter_navn { get; set; }
        public string forfatter_fornavn { get; set; }
        public string forfatter_efternavn { get; set; }
        public string forfatter_profileLink_Large { get; set; }
        public string forfatter_profileLink_Medium { get; set; }
        public string forfatter_profileLink_Small { get; set; }
    }
}
