//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GUlevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_GUlevel()
        {
            this.DEA_KDWS_GUseriesLevel = new HashSet<DEA_KDWS_GUseriesLevel>();
            this.DEA_KDWS_GUProductLevels = new HashSet<DEA_KDWS_GUProductLevels>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public Nullable<int> niveau { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> kategori_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUseriesLevel> DEA_KDWS_GUseriesLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUProductLevels> DEA_KDWS_GUProductLevels { get; set; }
        public virtual DEA_KDWS_GUcategory DEA_KDWS_GUcategory { get; set; }
    }
}
