//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_HRproductcontributors
    {
        public string vare_id { get; set; }
        public string contributor_id { get; set; }
        public int role_id { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int firmpers_stamdata_sortorder { get; set; }
    
        public virtual DEA_KDWS_HRContributors DEA_KDWS_HRContributors { get; set; }
        public virtual DEA_KDWS_HRroles DEA_KDWS_HRroles { get; set; }
        public virtual DEA_KDWS_HRproduct DEA_KDWS_HRproduct { get; set; }
    }
}
