//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_ROSillustrator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_ROSillustrator()
        {
            this.DEA_KDWS_ROSwork = new HashSet<DEA_KDWS_ROSwork>();
        }
    
        public string illustrator_id { get; set; }
        public string illustrator_navn { get; set; }
        public string illustrator_langbeskrivelse { get; set; }
        public string illustrator_foto_lille { get; set; }
        public string illustrator_foto_stor { get; set; }
        public string illustrator_fornavn { get; set; }
        public string illustrator_efternavn { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROSwork> DEA_KDWS_ROSwork { get; set; }
    }
}
