//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GUBundleMembership
    {
        public int Id { get; set; }
        public string BundleId { get; set; }
        public int CampaignId { get; set; }
        public string MembershipPath { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual DEA_KDWS_GUBundle DEA_KDWS_GUBundle { get; set; }
    }
}
