//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_MUNKcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_MUNKcategory()
        {
            this.DEA_KDWS_MUNKcategory1 = new HashSet<DEA_KDWS_MUNKcategory>();
            this.DEA_KDWS_MUNKProductCategories = new HashSet<DEA_KDWS_MUNKProductCategories>();
            this.DEA_KDWS_MUNKSerieCategories = new HashSet<DEA_KDWS_MUNKSerieCategories>();
            this.DEA_KDWS_MUNKlevel = new HashSet<DEA_KDWS_MUNKlevel>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public short niveau { get; set; }
        public string sti { get; set; }
        public string noegle { get; set; }
        public string noegle_2 { get; set; }
        public Nullable<int> parent { get; set; }
        public string parent_sti { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string website_sti { get; set; }
        public string website_sti_parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_MUNKcategory> DEA_KDWS_MUNKcategory1 { get; set; }
        public virtual DEA_KDWS_MUNKcategory DEA_KDWS_MUNKcategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_MUNKProductCategories> DEA_KDWS_MUNKProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_MUNKSerieCategories> DEA_KDWS_MUNKSerieCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_MUNKlevel> DEA_KDWS_MUNKlevel { get; set; }
    }
}
