//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_HRattachments
    {
        public int id { get; set; }
        public string vare { get; set; }
        public string sampleURL { get; set; }
        public string fil { get; set; }
        public string filtype { get; set; }
        public string type { get; set; }
        public string kategori { get; set; }
        public string beskrivelse { get; set; }
        public string dmz_url { get; set; }
        public int kd_id { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public decimal kd_slettet { get; set; }
        public System.DateTime kd_oprettet { get; set; }
        public Nullable<bool> is_secured { get; set; }
    
        public virtual DEA_KDWS_HRproduct DEA_KDWS_HRproduct { get; set; }
    }
}
