//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GDKPresse_Vare
    {
        public string vare_id { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string kortbeskrivelse { get; set; }
        public string langbeskrivelse { get; set; }
        public string sider { get; set; }
        public string forside { get; set; }
        public string ISBN13 { get; set; }
        public string ostSBN { get; set; }
        public string titel { get; set; }
        public string undertitel { get; set; }
        public Nullable<int> udgave { get; set; }
        public string medietype { get; set; }
        public Nullable<System.DateTime> udgivelsesdato { get; set; }
        public string Oversaetter { get; set; }
        public string illustrator { get; set; }
        public string omslagsgrafiker { get; set; }
        public Nullable<decimal> vejledende_pris { get; set; }
        public string status { get; set; }
        public string organisationname { get; set; }
        public string kontaktperson_navn { get; set; }
        public string kontaktperson_mail { get; set; }
        public string kontaktperson_tlf { get; set; }
        public Nullable<bool> Publish2Pressesite { get; set; }
        public Nullable<bool> IsImageReadyInMMS { get; set; }
        public Nullable<bool> IsNewTitle { get; set; }
    }
}
