//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_HRseries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_HRseries()
        {
            this.DEA_KDWS_HRproductseries = new HashSet<DEA_KDWS_HRproductseries>();
            this.DEA_KDWS_HRSerieCategories = new HashSet<DEA_KDWS_HRSerieCategories>();
            this.DEA_KDWS_HRseriesLevel = new HashSet<DEA_KDWS_HRseriesLevel>();
            this.DEA_KDWS_HRseries1 = new HashSet<DEA_KDWS_HRseries>();
            this.DEA_KDWS_HRserieAreas = new HashSet<DEA_KDWS_HRserieAreas>();
            this.DEA_KDWS_HRserieSubAreas = new HashSet<DEA_KDWS_HRserieSubAreas>();
            this.DEA_KDWS_HRserieSubjects = new HashSet<DEA_KDWS_HRserieSubjects>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public short niveau { get; set; }
        public string sti { get; set; }
        public Nullable<bool> internet { get; set; }
        public string webadresse { get; set; }
        public string webkoncept { get; set; }
        public string beskrivelse { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string parent_sti { get; set; }
        public string forlag { get; set; }
        public string afdeling { get; set; }
        public string redaktion { get; set; }
        public bool Is_Image_Uploaded { get; set; }
        public int kd_id { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public decimal kd_slettet { get; set; }
        public System.DateTime kd_oprettet { get; set; }
        public decimal Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRproductseries> DEA_KDWS_HRproductseries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRSerieCategories> DEA_KDWS_HRSerieCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRseriesLevel> DEA_KDWS_HRseriesLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRseries> DEA_KDWS_HRseries1 { get; set; }
        public virtual DEA_KDWS_HRseries DEA_KDWS_HRseries2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRserieAreas> DEA_KDWS_HRserieAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRserieSubAreas> DEA_KDWS_HRserieSubAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRserieSubjects> DEA_KDWS_HRserieSubjects { get; set; }
    }
}
