//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GDKseries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_GDKseries()
        {
            this.DEA_KDWS_GDKproductseries = new HashSet<DEA_KDWS_GDKproductseries>();
            this.DEA_KDWS_GDKSerieCategories = new HashSet<DEA_KDWS_GDKSerieCategories>();
            this.DEA_KDWS_GDKseries1 = new HashSet<DEA_KDWS_GDKseries>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public short niveau { get; set; }
        public string sti { get; set; }
        public Nullable<bool> internet { get; set; }
        public string webadresse { get; set; }
        public string webkoncept { get; set; }
        public string beskrivelse { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string parent_sti { get; set; }
        public string forlag { get; set; }
        public string afdeling { get; set; }
        public string redaktion { get; set; }
        public bool Is_Image_Uploaded { get; set; }
        public int kd_id { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public decimal kd_slettet { get; set; }
        public System.DateTime kd_oprettet { get; set; }
        public decimal Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GDKproductseries> DEA_KDWS_GDKproductseries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GDKSerieCategories> DEA_KDWS_GDKSerieCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GDKseries> DEA_KDWS_GDKseries1 { get; set; }
        public virtual DEA_KDWS_GDKseries DEA_KDWS_GDKseries2 { get; set; }
    }
}
