//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_ROSwork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_ROSwork()
        {
            this.DEA_KDWS_ROSvare = new HashSet<DEA_KDWS_ROSvare>();
            this.DEA_KDWS_ROSforfatter = new HashSet<DEA_KDWS_ROSforfatter>();
            this.DEA_KDWS_ROShierarki = new HashSet<DEA_KDWS_ROShierarki>();
            this.DEA_KDWS_ROSillustrator = new HashSet<DEA_KDWS_ROSillustrator>();
        }
    
        public int work_id { get; set; }
        public string titel { get; set; }
        public string undertitel { get; set; }
        public string langbeskrivelse { get; set; }
        public Nullable<System.DateTime> Oprettelsesdato { get; set; }
        public Nullable<System.DateTime> Opdateringsdato { get; set; }
        public Nullable<System.DateTime> publiceringsdato { get; set; }
        public string forside_Wstr_lille { get; set; }
        public string forside_Wstr_stor { get; set; }
        public int publisher_id { get; set; }
        public string illustrator_raekkefolge { get; set; }
        public string forfatter_raekkefolge { get; set; }
    
        public virtual DEA_KDWS_ROSpublisher DEA_KDWS_ROSpublisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROSvare> DEA_KDWS_ROSvare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROSforfatter> DEA_KDWS_ROSforfatter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROShierarki> DEA_KDWS_ROShierarki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROSillustrator> DEA_KDWS_ROSillustrator { get; set; }
    }
}
