//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GPluslevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_GPluslevel()
        {
            this.DEA_KDWS_GPlusseriesLevel = new HashSet<DEA_KDWS_GPlusseriesLevel>();
            this.DEA_KDWS_GPlusProductLevels = new HashSet<DEA_KDWS_GPlusProductLevels>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public Nullable<int> niveau { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> kategori_id { get; set; }
    
        public virtual DEA_KDWS_GPluscategory DEA_KDWS_GPluscategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GPlusseriesLevel> DEA_KDWS_GPlusseriesLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GPlusProductLevels> DEA_KDWS_GPlusProductLevels { get; set; }
    }
}
