//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_HRlevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_HRlevel()
        {
            this.DEA_KDWS_HRseriesLevel = new HashSet<DEA_KDWS_HRseriesLevel>();
            this.DEA_KDWS_HRProductLevels = new HashSet<DEA_KDWS_HRProductLevels>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public Nullable<int> niveau { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> kategori_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRseriesLevel> DEA_KDWS_HRseriesLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRProductLevels> DEA_KDWS_HRProductLevels { get; set; }
        public virtual DEA_KDWS_HRcategory DEA_KDWS_HRcategory { get; set; }
    }
}
