//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GDKPresse_Kategori
    {
        public string kategori_id { get; set; }
        public string kategori_path { get; set; }
        public string kategori_navn { get; set; }
        public string kategori_type { get; set; }
        public Nullable<int> Kategori_order { get; set; }
    }
}
