//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_HRcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_HRcategory()
        {
            this.DEA_KDWS_HRcategory1 = new HashSet<DEA_KDWS_HRcategory>();
            this.DEA_KDWS_HRProductCategories = new HashSet<DEA_KDWS_HRProductCategories>();
            this.DEA_KDWS_HRSerieCategories = new HashSet<DEA_KDWS_HRSerieCategories>();
            this.DEA_KDWS_HRlevel = new HashSet<DEA_KDWS_HRlevel>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public short niveau { get; set; }
        public string sti { get; set; }
        public string noegle { get; set; }
        public string noegle_2 { get; set; }
        public Nullable<int> parent { get; set; }
        public string parent_sti { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string website_sti { get; set; }
        public string website_sti_parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRcategory> DEA_KDWS_HRcategory1 { get; set; }
        public virtual DEA_KDWS_HRcategory DEA_KDWS_HRcategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRProductCategories> DEA_KDWS_HRProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRSerieCategories> DEA_KDWS_HRSerieCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_HRlevel> DEA_KDWS_HRlevel { get; set; }
    }
}
