//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_ROSpressForfatter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_ROSpressForfatter()
        {
            this.DEA_KDWS_ROSpressMateriale = new HashSet<DEA_KDWS_ROSpressMateriale>();
            this.DEA_KDWS_ROSpressVare = new HashSet<DEA_KDWS_ROSpressVare>();
        }
    
        public string forfatter_id { get; set; }
        public string forfatter_navn { get; set; }
        public string forfatter_fornavn { get; set; }
        public string forfatter_efternavn { get; set; }
        public string forfatter_profileLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROSpressMateriale> DEA_KDWS_ROSpressMateriale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROSpressVare> DEA_KDWS_ROSpressVare { get; set; }
    }
}
