//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_ROSvare
    {
        public string vare_id { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string langbeskrivelse { get; set; }
        public Nullable<int> sider { get; set; }
        public string forside_Wstr_lille { get; set; }
        public string forside_Wstr_stor { get; set; }
        public string ISBN13 { get; set; }
        public string titel { get; set; }
        public string undertitel { get; set; }
        public Nullable<int> udgave { get; set; }
        public string medietype { get; set; }
        public Nullable<System.DateTime> udgivelsesdato { get; set; }
        public string Oversaetter { get; set; }
        public string illustrator_raekkefolge { get; set; }
        public string omslagsgrafiker { get; set; }
        public string vejledende_pris { get; set; }
        public string status { get; set; }
        public string ITunesLink { get; set; }
        public string AndroidLink { get; set; }
        public Nullable<int> work_id { get; set; }
        public string materialetype { get; set; }
        public string SEO_Text { get; set; }
        public Nullable<int> lagertal { get; set; }
        public string oplaeser { get; set; }
        public string forfatter_raekkefolge { get; set; }
        public string omslagsIllustrator { get; set; }
    
        public virtual DEA_KDWS_ROSwork DEA_KDWS_ROSwork { get; set; }
    }
}
