//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GUseries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_GUseries()
        {
            this.DEA_KDWS_GUproductseries = new HashSet<DEA_KDWS_GUproductseries>();
            this.DEA_KDWS_GUSerieCategories = new HashSet<DEA_KDWS_GUSerieCategories>();
            this.DEA_KDWS_GUseriesLevel = new HashSet<DEA_KDWS_GUseriesLevel>();
            this.DEA_KDWS_GUseries1 = new HashSet<DEA_KDWS_GUseries>();
            this.DEA_KDWS_GUserieAreas = new HashSet<DEA_KDWS_GUserieAreas>();
            this.DEA_KDWS_GUserieSubAreas = new HashSet<DEA_KDWS_GUserieSubAreas>();
            this.DEA_KDWS_GUserieSubjects = new HashSet<DEA_KDWS_GUserieSubjects>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public short niveau { get; set; }
        public string sti { get; set; }
        public Nullable<bool> internet { get; set; }
        public string webadresse { get; set; }
        public string webkoncept { get; set; }
        public string beskrivelse { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string parent_sti { get; set; }
        public string forlag { get; set; }
        public string afdeling { get; set; }
        public bool Is_Image_Uploaded { get; set; }
        public string redaktion { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public decimal kd_slettet { get; set; }
        public System.DateTime kd_oprettet { get; set; }
        public decimal Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUproductseries> DEA_KDWS_GUproductseries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUSerieCategories> DEA_KDWS_GUSerieCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUseriesLevel> DEA_KDWS_GUseriesLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUseries> DEA_KDWS_GUseries1 { get; set; }
        public virtual DEA_KDWS_GUseries DEA_KDWS_GUseries2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUserieAreas> DEA_KDWS_GUserieAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUserieSubAreas> DEA_KDWS_GUserieSubAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GUserieSubjects> DEA_KDWS_GUserieSubjects { get; set; }
    }
}
