//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_ROSpressVare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_ROSpressVare()
        {
            this.DEA_KDWS_ROSpressForfatter = new HashSet<DEA_KDWS_ROSpressForfatter>();
        }
    
        public string vare_id { get; set; }
        public string ISBN13 { get; set; }
        public string ostSBN { get; set; }
        public string titel { get; set; }
        public Nullable<int> udgave { get; set; }
        public Nullable<System.DateTime> udgivelsesdato { get; set; }
        public string organisationname { get; set; }
        public Nullable<int> IsImageReadyInMMS { get; set; }
        public string forside_title_link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_ROSpressForfatter> DEA_KDWS_ROSpressForfatter { get; set; }
    }
}
