//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GPlusProductThemacode
    {
        public int vare_themacode_Id { get; set; }
        public int ThemaCodeId { get; set; }
        public string Vare { get; set; }
        public Nullable<bool> IsPrimaryCategory { get; set; }
        public System.DateTime kd_oprettet { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual DEA_KDWS_GPlusThemacode DEA_KDWS_GPlusThemacode { get; set; }
        public virtual DEA_KDWS_GPlusproduct DEA_KDWS_GPlusproduct { get; set; }
    }
}
