//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GGA_Vare
    {
        public string vare_id { get; set; }
        public string ISBN13 { get; set; }
        public Nullable<int> ostSBN { get; set; }
        public string titel { get; set; }
        public short udgave { get; set; }
        public System.DateTime udgivelsesdato { get; set; }
        public string organisationname { get; set; }
        public int IsImageReadyInMMS { get; set; }
        public Nullable<int> forside_title_link { get; set; }
        public string illustrator { get; set; }
        public string translator { get; set; }
        public string Publisher { get; set; }
        public string No_of_Pages { get; set; }
        public string Year_of_Publication_ { get; set; }
        public string WebText { get; set; }
    }
}
