//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_MUNKproductauthors
    {
        public string vare_id { get; set; }
        public string forfatter_id { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int firmpers_stamdata_sortorder { get; set; }
    
        public virtual DEA_KDWS_MUNKauthors DEA_KDWS_MUNKauthors { get; set; }
        public virtual DEA_KDWS_MUNKproduct DEA_KDWS_MUNKproduct { get; set; }
    }
}
