//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_HRseriesLevelLog
    {
        public int ID { get; set; }
        public int serie_id { get; set; }
        public int level_id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Action { get; set; }
    }
}
