//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEA_KDWS_GDKcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEA_KDWS_GDKcategory()
        {
            this.DEA_KDWS_GDKcategory1 = new HashSet<DEA_KDWS_GDKcategory>();
            this.DEA_KDWS_GDKSerieCategories = new HashSet<DEA_KDWS_GDKSerieCategories>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public short niveau { get; set; }
        public string sti { get; set; }
        public string noegle { get; set; }
        public string noegle_2 { get; set; }
        public Nullable<int> parent { get; set; }
        public string parent_sti { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string website_sti { get; set; }
        public string website_sti_parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GDKcategory> DEA_KDWS_GDKcategory1 { get; set; }
        public virtual DEA_KDWS_GDKcategory DEA_KDWS_GDKcategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEA_KDWS_GDKSerieCategories> DEA_KDWS_GDKSerieCategories { get; set; }
    }
}
