//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class pakker
    {
        public string pakke { get; set; }
        public string vare { get; set; }
        public decimal pris_uden_moms { get; set; }
        public int antal { get; set; }
        public int sequence { get; set; }
        public int id { get; set; }
        public Nullable<decimal> discount_percentage { get; set; }
    }
}
