//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class varer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public varer()
        {
            this.CampaignItem = new HashSet<CampaignItem>();
            this.supplerende_materialer = new HashSet<supplerende_materialer>();
            this.portersitekategorier = new HashSet<portersitekategorier>();
        }
    
        public string id { get; set; }
        public string subtype { get; set; }
        public string varenummer { get; set; }
        public short udgave { get; set; }
        public short oplag { get; set; }
        public Nullable<decimal> udgivet { get; set; }
        public string titel { get; set; }
        public string undertitel { get; set; }
        public string originaltitel { get; set; }
        public string bogtype { get; set; }
        public string sideantal { get; set; }
        public string medieantal { get; set; }
        public string spilletid { get; set; }
        public string webname { get; set; }
        public string originaludgavens_isbn { get; set; }
        public string tilgrundliggende_udgaves_isbn13 { get; set; }
        public string forrige_udgaves_isbn { get; set; }
        public string kategori { get; set; }
        public string internet_kategorier_niveau_2 { get; set; }
        public System.DateTime udgivelsesdato { get; set; }
        public Nullable<System.DateTime> udgivelsesdato_oplag_1 { get; set; }
        public Nullable<decimal> internet { get; set; }
        public Nullable<decimal> pris_uden_moms { get; set; }
        public Nullable<decimal> gratis { get; set; }
        public Nullable<int> lagertal { get; set; }
        public string kn1 { get; set; }
        public Nullable<decimal> titel_uden_lager { get; set; }
        public Nullable<decimal> gennemsynseksemplar { get; set; }
        public string webadresse { get; set; }
        public Nullable<decimal> specialfiler_tilknyttet { get; set; }
        public string adgangskontrol { get; set; }
        public string unic_projekt_id { get; set; }
        public string unic_projekt_navn { get; set; }
        public Nullable<int> unic_subscription_duration { get; set; }
        public Nullable<int> ekey_subscription_duration { get; set; }
        public string ekey_activation_type { get; set; }
        public string medietype { get; set; }
        public string produktvariant { get; set; }
        public string undskyldningskode { get; set; }
        public string rabatgruppe { get; set; }
        public string boghandlergruppe { get; set; }
        public string forfattere { get; set; }
        public string oversaettere { get; set; }
        public string indlaesere { get; set; }
        public string illustratorer { get; set; }
        public string grafikere { get; set; }
        public string omslagsillustratorer { get; set; }
        public string omslagsgrafikere { get; set; }
        public string fagredaktoerer { get; set; }
        public string serier { get; set; }
        public string beskrivelse { get; set; }
        public string forlag { get; set; }
        public string afdeling { get; set; }
        public string redaktion { get; set; }
        public Nullable<int> stamblad { get; set; }
        public int kd_id { get; set; }
        public System.DateTime kd_gyldig_fra { get; set; }
        public decimal kd_slettet { get; set; }
        public System.DateTime kd_oprettet { get; set; }
        public string udkommerforlag { get; set; }
        public string GDK_simplemedietype { get; set; }
        public string simplemedietype { get; set; }
        public Nullable<bool> værk { get; set; }
        public string værk_id { get; set; }
        public string ituneslink { get; set; }
        public string GDK_status { get; set; }
        public string distributor { get; set; }
        public Nullable<bool> pakke { get; set; }
        public string UdgivelsesDatoAar { get; set; }
        public Nullable<decimal> pris_med_moms { get; set; }
        public string rosinante_menukey { get; set; }
        public string kortbeskrivelse { get; set; }
        public string langbeskrivelse { get; set; }
        public string illustrationURL { get; set; }
        public string klassetrin { get; set; }
        public string redaktoer { get; set; }
        public string anmeldelser { get; set; }
        public string SEOdescription { get; set; }
        public string SEOkeywords { get; set; }
        public string fag { get; set; }
        public string omslag { get; set; }
        public string serie { get; set; }
        public Nullable<int> Fysisk_bredte_mm { get; set; }
        public Nullable<int> Fysisk_hoejde_mm { get; set; }
        public Nullable<int> Fysisk_dybte_mm { get; set; }
        public Nullable<int> Fysisk_vaegt_gram { get; set; }
        public string Forlagskode { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string KortbeskrivelseXS { get; set; }
        public string langbeskrivelse_tekst { get; set; }
        public string originaludgavens_isbn13 { get; set; }
        public Nullable<bool> inaktiv { get; set; }
        public Nullable<bool> licenserOprettet { get; set; }
        public string ordreVarenr { get; set; }
        public string SEOtitle { get; set; }
        public string GU_simplemedietype { get; set; }
        public string bagsidetekst { get; set; }
        public string katalogtekst { get; set; }
        public Nullable<int> ProduktKat_1 { get; set; }
        public string pristype { get; set; }
        public string kd_medietype { get; set; }
        public string kd_adgangskontrol { get; set; }
        public Nullable<int> kd_lagertal { get; set; }
        public string kd_unic_projekt_navn { get; set; }
        public Nullable<bool> is_email_required { get; set; }
        public Nullable<decimal> rap_pris_uden_moms { get; set; }
        public string Bladreboger { get; set; }
        public bool IsNextPrintRunPlanned { get; set; }
        public string PrintingNum { get; set; }
        public Nullable<double> Gross_weight { get; set; }
        public Nullable<double> Net_weight { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Thickness_depth { get; set; }
        public Nullable<System.DateTime> FirstPrintPublishDate { get; set; }
        public string Imprint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignItem> CampaignItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplerende_materialer> supplerende_materialer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portersitekategorier> portersitekategorier { get; set; }
    }
}
