//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class webshops_instruktoerer
    {
        public int id { get; set; }
        public string navn { get; set; }
        public System.DateTime kd_gyldig_fra { get; set; }
        public decimal kd_slettet { get; set; }
    }
}
