//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class webshops_kurser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public webshops_kurser()
        {
            this.webshops_kursus_instruktoerer = new HashSet<webshops_kursus_instruktoerer>();
            this.webshops_kursus_kategorier = new HashSet<webshops_kursus_kategorier>();
        }
    
        public int id { get; set; }
        public string titel { get; set; }
        public string undertitel { get; set; }
        public Nullable<System.DateTime> afholdes { get; set; }
        public Nullable<System.DateTime> publiceres { get; set; }
        public Nullable<System.DateTime> afpubliceres { get; set; }
        public Nullable<decimal> pris_uden_moms { get; set; }
        public decimal pris_med_moms { get; set; }
        public string type { get; set; }
        public string fag { get; set; }
        public string uddannelse { get; set; }
        public string sted { get; set; }
        public string beskrivelse { get; set; }
        public string billed_url { get; set; }
        public string system_url { get; set; }
        public string kontakt_url { get; set; }
        public string forlag { get; set; }
        public string afdeling { get; set; }
        public string redaktion { get; set; }
        public System.DateTime kd_gyldig_fra { get; set; }
        public decimal kd_slettet { get; set; }
        public string starter { get; set; }
        public string slutter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webshops_kursus_instruktoerer> webshops_kursus_instruktoerer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webshops_kursus_kategorier> webshops_kursus_kategorier { get; set; }
    }
}
