//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.KoncernData
{
    using System;
    using System.Collections.Generic;
    
    public partial class work
    {
        public int WorkId { get; set; }
        public string Title { get; set; }
        public string WorkLabel { get; set; }
        public System.DateTime Created { get; set; }
        public bool kd_slettet { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
    }
}
