//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyldendal.Api.CoreData.DataAccess.ShopAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublizonMetadata
    {
        public string ISBN { get; set; }
        public string SampleURL { get; set; }
        public string PublizonIdentifier { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
