//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSImageService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMSDownloadOptions", Namespace="http://tempuri.org/")]
    public enum MMSDownloadOptions : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Download = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DownloadIfReal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoNotDownload = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMSImageDTO", Namespace="http://tempuri.org/")]
    public partial class MMSImageDTO : object
    {
        
        private MMSImageService.MMSImageType ImageTypeField;
        
        private byte[] ImageBytesField;
        
        private string MimeTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MMSImageService.MMSImageType ImageType
        {
            get
            {
                return this.ImageTypeField;
            }
            set
            {
                this.ImageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ImageBytes
        {
            get
            {
                return this.ImageBytesField;
            }
            set
            {
                this.ImageBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMSImageType", Namespace="http://tempuri.org/")]
    public enum MMSImageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Real = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Missing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMSResource", Namespace="http://tempuri.org/")]
    public partial class MMSResource : object
    {
        
        private string FileNameField;
        
        private int FileSizeField;
        
        private string FileExtensionField;
        
        private string ConsumerTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FileSize
        {
            get
            {
                return this.FileSizeField;
            }
            set
            {
                this.FileSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ConsumerToken
        {
            get
            {
                return this.ConsumerTokenField;
            }
            set
            {
                this.ConsumerTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VariantDto", Namespace="http://tempuri.org/")]
    public partial class VariantDto : object
    {
        
        private string ImagetokenField;
        
        private string ConsumertokenField;
        
        private string VarianttokenField;
        
        private string OrganizationNameField;
        
        private string WidthField;
        
        private string HeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Imagetoken
        {
            get
            {
                return this.ImagetokenField;
            }
            set
            {
                this.ImagetokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Consumertoken
        {
            get
            {
                return this.ConsumertokenField;
            }
            set
            {
                this.ConsumertokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Varianttoken
        {
            get
            {
                return this.VarianttokenField;
            }
            set
            {
                this.VarianttokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OrganizationName
        {
            get
            {
                return this.OrganizationNameField;
            }
            set
            {
                this.OrganizationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MMSImageService.MMSImageServiceSoap")]
    public interface MMSImageServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMMSImage", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.GetMMSImageResponse> GetMMSImageAsync(MMSImageService.GetMMSImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsImageUploadedInMMS", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.IsImageUploadedInMMSResponse> IsImageUploadedInMMSAsync(MMSImageService.IsImageUploadedInMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdatedImages", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.GetUpdatedImagesResponse> GetUpdatedImagesAsync(MMSImageService.GetUpdatedImagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUpdateLog", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.DeleteUpdateLogResponse> DeleteUpdateLogAsync(MMSImageService.DeleteUpdateLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResourceDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.GetResourceDetailsResponse> GetResourceDetailsAsync(MMSImageService.GetResourceDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsumerToken", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.GetConsumerTokenResponse> GetConsumerTokenAsync(MMSImageService.GetConsumerTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidImage", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.IsValidImageResponse> IsValidImageAsync(MMSImageService.IsValidImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVariantImages", ReplyAction="*")]
        System.Threading.Tasks.Task<MMSImageService.GetVariantImagesResponse> GetVariantImagesAsync(MMSImageService.GetVariantImagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMMSImageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMMSImage", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetMMSImageRequestBody Body;
        
        public GetMMSImageRequest()
        {
        }
        
        public GetMMSImageRequest(MMSImageService.GetMMSImageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMMSImageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public MMSImageService.MMSDownloadOptions options;
        
        public GetMMSImageRequestBody()
        {
        }
        
        public GetMMSImageRequestBody(string url, MMSImageService.MMSDownloadOptions options)
        {
            this.url = url;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMMSImageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMMSImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetMMSImageResponseBody Body;
        
        public GetMMSImageResponse()
        {
        }
        
        public GetMMSImageResponse(MMSImageService.GetMMSImageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMMSImageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MMSImageService.MMSImageDTO GetMMSImageResult;
        
        public GetMMSImageResponseBody()
        {
        }
        
        public GetMMSImageResponseBody(MMSImageService.MMSImageDTO GetMMSImageResult)
        {
            this.GetMMSImageResult = GetMMSImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsImageUploadedInMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsImageUploadedInMMS", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.IsImageUploadedInMMSRequestBody Body;
        
        public IsImageUploadedInMMSRequest()
        {
        }
        
        public IsImageUploadedInMMSRequest(MMSImageService.IsImageUploadedInMMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsImageUploadedInMMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imageName;
        
        public IsImageUploadedInMMSRequestBody()
        {
        }
        
        public IsImageUploadedInMMSRequestBody(string imageName)
        {
            this.imageName = imageName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsImageUploadedInMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsImageUploadedInMMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.IsImageUploadedInMMSResponseBody Body;
        
        public IsImageUploadedInMMSResponse()
        {
        }
        
        public IsImageUploadedInMMSResponse(MMSImageService.IsImageUploadedInMMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsImageUploadedInMMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsImageUploadedInMMSResult;
        
        public IsImageUploadedInMMSResponseBody()
        {
        }
        
        public IsImageUploadedInMMSResponseBody(bool IsImageUploadedInMMSResult)
        {
            this.IsImageUploadedInMMSResult = IsImageUploadedInMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpdatedImagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpdatedImages", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetUpdatedImagesRequestBody Body;
        
        public GetUpdatedImagesRequest()
        {
        }
        
        public GetUpdatedImagesRequest(MMSImageService.GetUpdatedImagesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUpdatedImagesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<System.DateTime> startDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> endDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string variant;
        
        public GetUpdatedImagesRequestBody()
        {
        }
        
        public GetUpdatedImagesRequestBody(System.Nullable<System.DateTime> startDateTime, System.Nullable<System.DateTime> endDateTime, string variant)
        {
            this.startDateTime = startDateTime;
            this.endDateTime = endDateTime;
            this.variant = variant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpdatedImagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpdatedImagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetUpdatedImagesResponseBody Body;
        
        public GetUpdatedImagesResponse()
        {
        }
        
        public GetUpdatedImagesResponse(MMSImageService.GetUpdatedImagesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUpdatedImagesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MMSImageService.ArrayOfString GetUpdatedImagesResult;
        
        public GetUpdatedImagesResponseBody()
        {
        }
        
        public GetUpdatedImagesResponseBody(MMSImageService.ArrayOfString GetUpdatedImagesResult)
        {
            this.GetUpdatedImagesResult = GetUpdatedImagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUpdateLogRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUpdateLog", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.DeleteUpdateLogRequestBody Body;
        
        public DeleteUpdateLogRequest()
        {
        }
        
        public DeleteUpdateLogRequest(MMSImageService.DeleteUpdateLogRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUpdateLogRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MMSImageService.ArrayOfString isbnList;
        
        public DeleteUpdateLogRequestBody()
        {
        }
        
        public DeleteUpdateLogRequestBody(MMSImageService.ArrayOfString isbnList)
        {
            this.isbnList = isbnList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUpdateLogResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUpdateLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.DeleteUpdateLogResponseBody Body;
        
        public DeleteUpdateLogResponse()
        {
        }
        
        public DeleteUpdateLogResponse(MMSImageService.DeleteUpdateLogResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteUpdateLogResponseBody
    {
        
        public DeleteUpdateLogResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourceDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResourceDetails", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetResourceDetailsRequestBody Body;
        
        public GetResourceDetailsRequest()
        {
        }
        
        public GetResourceDetailsRequest(MMSImageService.GetResourceDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResourceDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string consumerName;
        
        public GetResourceDetailsRequestBody()
        {
        }
        
        public GetResourceDetailsRequestBody(string isbn, string consumerName)
        {
            this.isbn = isbn;
            this.consumerName = consumerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourceDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResourceDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetResourceDetailsResponseBody Body;
        
        public GetResourceDetailsResponse()
        {
        }
        
        public GetResourceDetailsResponse(MMSImageService.GetResourceDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResourceDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MMSImageService.MMSResource GetResourceDetailsResult;
        
        public GetResourceDetailsResponseBody()
        {
        }
        
        public GetResourceDetailsResponseBody(MMSImageService.MMSResource GetResourceDetailsResult)
        {
            this.GetResourceDetailsResult = GetResourceDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConsumerTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConsumerToken", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetConsumerTokenRequestBody Body;
        
        public GetConsumerTokenRequest()
        {
        }
        
        public GetConsumerTokenRequest(MMSImageService.GetConsumerTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConsumerTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consumerName;
        
        public GetConsumerTokenRequestBody()
        {
        }
        
        public GetConsumerTokenRequestBody(string consumerName)
        {
            this.consumerName = consumerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConsumerTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConsumerTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetConsumerTokenResponseBody Body;
        
        public GetConsumerTokenResponse()
        {
        }
        
        public GetConsumerTokenResponse(MMSImageService.GetConsumerTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConsumerTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetConsumerTokenResult;
        
        public GetConsumerTokenResponseBody()
        {
        }
        
        public GetConsumerTokenResponseBody(string GetConsumerTokenResult)
        {
            this.GetConsumerTokenResult = GetConsumerTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidImageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidImage", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.IsValidImageRequestBody Body;
        
        public IsValidImageRequest()
        {
        }
        
        public IsValidImageRequest(MMSImageService.IsValidImageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsValidImageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imageName;
        
        public IsValidImageRequestBody()
        {
        }
        
        public IsValidImageRequestBody(string imageName)
        {
            this.imageName = imageName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidImageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.IsValidImageResponseBody Body;
        
        public IsValidImageResponse()
        {
        }
        
        public IsValidImageResponse(MMSImageService.IsValidImageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsValidImageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsValidImageResult;
        
        public IsValidImageResponseBody()
        {
        }
        
        public IsValidImageResponseBody(bool IsValidImageResult)
        {
            this.IsValidImageResult = IsValidImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVariantImagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVariantImages", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetVariantImagesRequestBody Body;
        
        public GetVariantImagesRequest()
        {
        }
        
        public GetVariantImagesRequest(MMSImageService.GetVariantImagesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVariantImagesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        public GetVariantImagesRequestBody()
        {
        }
        
        public GetVariantImagesRequestBody(string isbn)
        {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVariantImagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVariantImagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MMSImageService.GetVariantImagesResponseBody Body;
        
        public GetVariantImagesResponse()
        {
        }
        
        public GetVariantImagesResponse(MMSImageService.GetVariantImagesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVariantImagesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MMSImageService.VariantDto[] GetVariantImagesResult;
        
        public GetVariantImagesResponseBody()
        {
        }
        
        public GetVariantImagesResponseBody(MMSImageService.VariantDto[] GetVariantImagesResult)
        {
            this.GetVariantImagesResult = GetVariantImagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MMSImageServiceSoapChannel : MMSImageService.MMSImageServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MMSImageServiceSoapClient : System.ServiceModel.ClientBase<MMSImageService.MMSImageServiceSoap>, MMSImageService.MMSImageServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MMSImageServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MMSImageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MMSImageServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MMSImageServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MMSImageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MMSImageServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MMSImageServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MMSImageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.GetMMSImageResponse> MMSImageService.MMSImageServiceSoap.GetMMSImageAsync(MMSImageService.GetMMSImageRequest request)
        {
            return base.Channel.GetMMSImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.GetMMSImageResponse> GetMMSImageAsync(string url, MMSImageService.MMSDownloadOptions options)
        {
            MMSImageService.GetMMSImageRequest inValue = new MMSImageService.GetMMSImageRequest();
            inValue.Body = new MMSImageService.GetMMSImageRequestBody();
            inValue.Body.url = url;
            inValue.Body.options = options;
            return ((MMSImageService.MMSImageServiceSoap)(this)).GetMMSImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.IsImageUploadedInMMSResponse> MMSImageService.MMSImageServiceSoap.IsImageUploadedInMMSAsync(MMSImageService.IsImageUploadedInMMSRequest request)
        {
            return base.Channel.IsImageUploadedInMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.IsImageUploadedInMMSResponse> IsImageUploadedInMMSAsync(string imageName)
        {
            MMSImageService.IsImageUploadedInMMSRequest inValue = new MMSImageService.IsImageUploadedInMMSRequest();
            inValue.Body = new MMSImageService.IsImageUploadedInMMSRequestBody();
            inValue.Body.imageName = imageName;
            return ((MMSImageService.MMSImageServiceSoap)(this)).IsImageUploadedInMMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.GetUpdatedImagesResponse> MMSImageService.MMSImageServiceSoap.GetUpdatedImagesAsync(MMSImageService.GetUpdatedImagesRequest request)
        {
            return base.Channel.GetUpdatedImagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.GetUpdatedImagesResponse> GetUpdatedImagesAsync(System.Nullable<System.DateTime> startDateTime, System.Nullable<System.DateTime> endDateTime, string variant)
        {
            MMSImageService.GetUpdatedImagesRequest inValue = new MMSImageService.GetUpdatedImagesRequest();
            inValue.Body = new MMSImageService.GetUpdatedImagesRequestBody();
            inValue.Body.startDateTime = startDateTime;
            inValue.Body.endDateTime = endDateTime;
            inValue.Body.variant = variant;
            return ((MMSImageService.MMSImageServiceSoap)(this)).GetUpdatedImagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.DeleteUpdateLogResponse> MMSImageService.MMSImageServiceSoap.DeleteUpdateLogAsync(MMSImageService.DeleteUpdateLogRequest request)
        {
            return base.Channel.DeleteUpdateLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.DeleteUpdateLogResponse> DeleteUpdateLogAsync(MMSImageService.ArrayOfString isbnList)
        {
            MMSImageService.DeleteUpdateLogRequest inValue = new MMSImageService.DeleteUpdateLogRequest();
            inValue.Body = new MMSImageService.DeleteUpdateLogRequestBody();
            inValue.Body.isbnList = isbnList;
            return ((MMSImageService.MMSImageServiceSoap)(this)).DeleteUpdateLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.GetResourceDetailsResponse> MMSImageService.MMSImageServiceSoap.GetResourceDetailsAsync(MMSImageService.GetResourceDetailsRequest request)
        {
            return base.Channel.GetResourceDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.GetResourceDetailsResponse> GetResourceDetailsAsync(string isbn, string consumerName)
        {
            MMSImageService.GetResourceDetailsRequest inValue = new MMSImageService.GetResourceDetailsRequest();
            inValue.Body = new MMSImageService.GetResourceDetailsRequestBody();
            inValue.Body.isbn = isbn;
            inValue.Body.consumerName = consumerName;
            return ((MMSImageService.MMSImageServiceSoap)(this)).GetResourceDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.GetConsumerTokenResponse> MMSImageService.MMSImageServiceSoap.GetConsumerTokenAsync(MMSImageService.GetConsumerTokenRequest request)
        {
            return base.Channel.GetConsumerTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.GetConsumerTokenResponse> GetConsumerTokenAsync(string consumerName)
        {
            MMSImageService.GetConsumerTokenRequest inValue = new MMSImageService.GetConsumerTokenRequest();
            inValue.Body = new MMSImageService.GetConsumerTokenRequestBody();
            inValue.Body.consumerName = consumerName;
            return ((MMSImageService.MMSImageServiceSoap)(this)).GetConsumerTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.IsValidImageResponse> MMSImageService.MMSImageServiceSoap.IsValidImageAsync(MMSImageService.IsValidImageRequest request)
        {
            return base.Channel.IsValidImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.IsValidImageResponse> IsValidImageAsync(string imageName)
        {
            MMSImageService.IsValidImageRequest inValue = new MMSImageService.IsValidImageRequest();
            inValue.Body = new MMSImageService.IsValidImageRequestBody();
            inValue.Body.imageName = imageName;
            return ((MMSImageService.MMSImageServiceSoap)(this)).IsValidImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MMSImageService.GetVariantImagesResponse> MMSImageService.MMSImageServiceSoap.GetVariantImagesAsync(MMSImageService.GetVariantImagesRequest request)
        {
            return base.Channel.GetVariantImagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MMSImageService.GetVariantImagesResponse> GetVariantImagesAsync(string isbn)
        {
            MMSImageService.GetVariantImagesRequest inValue = new MMSImageService.GetVariantImagesRequest();
            inValue.Body = new MMSImageService.GetVariantImagesRequestBody();
            inValue.Body.isbn = isbn;
            return ((MMSImageService.MMSImageServiceSoap)(this)).GetVariantImagesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MMSImageServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MMSImageServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MMSImageServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://test.multimediaservice.gyldendal.local/MMSImageService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MMSImageServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://test.multimediaservice.gyldendal.local/MMSImageService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MMSImageServiceSoap,
            
            MMSImageServiceSoap12,
        }
    }
}
